// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAL.PremiumCalculator.Data;

#nullable disable

namespace TAL.PremiumCalculator.Data.Migrations
{
    [DbContext(typeof(PremiumCalculatorContext))]
    [Migration("20230222001055_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TAL.PremiumCalculator.Data.Models.Occupation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OccupationRatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OccupationRatingId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OccupationRatingId1");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("TAL.PremiumCalculator.Data.Models.OccupationRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Factor")
                        .HasColumnType("float");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OccupationRatings");
                });

            modelBuilder.Entity("TAL.PremiumCalculator.Data.Models.Occupation", b =>
                {
                    b.HasOne("TAL.PremiumCalculator.Data.Models.OccupationRating", "OccupationRating")
                        .WithMany()
                        .HasForeignKey("OccupationRatingId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OccupationRating");
                });
#pragma warning restore 612, 618
        }
    }
}
