// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TAL.PremiumCalculator.Data;

#nullable disable

namespace TAL.PremiumCalculator.Data.Migrations
{
    [DbContext(typeof(PremiumCalculatorContext))]
    [Migration("20230222005050_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TAL.PremiumCalculator.Data.Models.Occupation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("OccupationRatingId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccupationRatingId");

                    b.ToTable("Occupations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("31c956d2-9d13-4b1c-b38a-233b3b3a8914"),
                            Name = "Cleaner",
                            OccupationRatingId = new Guid("25569b64-452b-40dd-b8f8-59b9eb239158")
                        },
                        new
                        {
                            Id = new Guid("35daebfb-58da-4bdd-8a49-7dd58d344d01"),
                            Name = "Doctor",
                            OccupationRatingId = new Guid("7f907568-0c7c-40b0-8782-fc99efdcd553")
                        },
                        new
                        {
                            Id = new Guid("6990e2de-8a01-401b-86ff-9b0bb83415f3"),
                            Name = "Author",
                            OccupationRatingId = new Guid("b7209ddc-eb32-4643-a797-bd11647f04f5")
                        },
                        new
                        {
                            Id = new Guid("0e25daed-d9e1-45ec-9f4c-4395c876de98"),
                            Name = "Farmer",
                            OccupationRatingId = new Guid("7e98cc49-cfdd-4c05-ab68-6d72f8989d3f")
                        },
                        new
                        {
                            Id = new Guid("d01375c9-7c2a-4ffa-b78b-38dd3d73e13e"),
                            Name = "Mechanic",
                            OccupationRatingId = new Guid("7e98cc49-cfdd-4c05-ab68-6d72f8989d3f")
                        },
                        new
                        {
                            Id = new Guid("a8a5224a-d571-4948-b2cf-a418f00be2d8"),
                            Name = "Florist",
                            OccupationRatingId = new Guid("25569b64-452b-40dd-b8f8-59b9eb239158")
                        });
                });

            modelBuilder.Entity("TAL.PremiumCalculator.Data.Models.OccupationRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Factor")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OccupationRatings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7f907568-0c7c-40b0-8782-fc99efdcd553"),
                            Factor = 1.0,
                            Name = "Professional"
                        },
                        new
                        {
                            Id = new Guid("b7209ddc-eb32-4643-a797-bd11647f04f5"),
                            Factor = 1.25,
                            Name = "White Collar"
                        },
                        new
                        {
                            Id = new Guid("25569b64-452b-40dd-b8f8-59b9eb239158"),
                            Factor = 1.5,
                            Name = "Light Manual"
                        },
                        new
                        {
                            Id = new Guid("7e98cc49-cfdd-4c05-ab68-6d72f8989d3f"),
                            Factor = 1.75,
                            Name = "Heavy Manual"
                        });
                });

            modelBuilder.Entity("TAL.PremiumCalculator.Data.Models.Occupation", b =>
                {
                    b.HasOne("TAL.PremiumCalculator.Data.Models.OccupationRating", "OccupationRating")
                        .WithMany()
                        .HasForeignKey("OccupationRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OccupationRating");
                });
#pragma warning restore 612, 618
        }
    }
}
